package com.pascal.anime_ku.model

import com.pascal.anime_ku.R

object SampleDataSource {
    val dummyAnimes = listOf(
        Anime(1, "Naruto Uzumaki", "Rasegan", "Junko Takeuchi", "Male", "Naruto", R.drawable.naruto,"Naruto Uzumaki (渦巻 鳴門, Uzumaki Naruto) adalah shinobi dari Konohagakure. Dia menjadi jinchūriki dari Ekor Sembilan pada hari kelahirannya — sebuah nasib yang menyebabkan dia dijauhi oleh sebagian besar penduduk Konoha sepanjang masa kecilnya. Setelah bergabung dengan Tim Kakashi, Naruto bekerja keras untuk mendapatkan pengakuan desa sambil mengejar mimpinya untuk menjadi Hokage."),
        Anime(2, "Sasuke Uciha", "Chidory", "Noriaki Sugiyama", "Male", "Naruto", R.drawable.sasuke,"Sasuke Uchiha (団扇 佐助, Uchiha Sasuke) adalah salah satu anggota terakhir klan Uchiha yang masih bertahan dari Konohagakure. Setelah kakaknya, Itachi, membantai klan mereka, Sasuke berusaha mewujudkan misinya dalam rangka untuk membalas dendam dengan membunuh Itachi."),
        Anime(3, "Kakashi Hatake", "Raikiri", "Kazuhiko Inoue", "Male", "Naruto", R.drawable.kakashi,"Kakashi dikenal luas sebagai ninja peniru (copy ninja). Kemampuan ini didapatnya dari sharingan yang di mata kirinya. Mata ini bisa membaca gerakan sampai tiga detik sebelum kejadian. Bisa juga sebagai media Doujutsu atau jutsu menggunakan mata yaitu Sharingan. Kabarnya Kakashi meniru 1000 jurus musuh dengan kemampuan ini."),

        Anime(4, "Son Goku", "Kamehameha", "Kirby Morrow", "Male", "DragonBall", R.drawable.goku,"Goku dikirim ke planet bumi ketika masih bayi pada awalnya dari planet Vegeta adalah untuk membinasakan seluruh makhluk hidup di bumi, mengingat Goku yang terlahir dengan nama Kakarot dan merupakan ksatria kelas rendah yg memiliki daya tempur di bawah rata-rata bayi Saiya lainnya, maka Goku di utus untuk membinasakan kehidupan di planet yang di dalamnya hampir tidak terdapat seseorang yang memiliki daya tempur yang tinggi. Goku diharapkan dapat membinasakan kehidupan di Bumi hanya dalam waktu hitungan bulan, karena ketika bulan purnama tiba bangsa Saiya dapat menunjukkan kekuatan sebenarnya yang dimiliki."),
        Anime(5, "Vegeta", "Galickun", "Ryō Horikawa", "Male", "DragonBall", R.drawable.vegeta,"Vegeta diperkenalkan sebagai pangeran angkuh dari ras Saiya (サイヤ人, Saiya-jin). Dia pergi ke bumi bersama rekannya Nappa dengan tujuan untuk menggunakan Dragon Ball untuk meminta keabadian.[16] Dia dan Nappa mengalahkan yang lain, tetapi kemudian Goku tiba setelah menyelesaikan latihannya dengan Tuan Kaio. Vegeta membunuh Nappa karena kalah dengan mudah dari Goku, tetapi Vegeta pun segera menyadari bahwa dia tidak sanggup menang melawan para pahlawan dan hampir tidak bisa lari hidup-hidup"),
        Anime(6, "Son Gohan", "Masenko", "Kirby Morrow", "Male", "DragonBall", R.drawable.gohan,"Gohan (孫悟飯 Son Gohan) adalah anak pertama dari Goku dan Chi-Chi. Karena memiliki campuran darah bangsa Saiya dan Bumi, maka dari kecil Gohan memiliki kekuatan yang sangat kuat (konon diketahui bahwa jika terjadi perkawinan silang antar bangsa Saiya dengan bangsa lain, maka keturunan yang dihasilkan akan memiliki tenaga yang sangat besar)."),

        Anime(7, "Monkey D. Luffy", "Gomu-gomu", "Mayumi Tanaka", "Male", "One Piece", R.drawable.luffy,"Monkey D. Luffy (モンキー･D･ルフィ, Monkii D. Rufi) adalah seorang karakter fiksi dan tokoh protagonis utama dalam serial anime dan manga One Piece karya Eiichiro Oda. [1] Ia merupakan putra kandung dari pemimpin Pasukan Revolusioner, Monkey D. Dragon, cucu kandung dari Angkatan Laut terkenal, Monkey D. Garp, putra angkat dari bandit gunung, Curly Dadan, dan saudara angkat dari Portgas D. Ace si \"Tinju Api\" dan Sabo. Tujuan hidupnya adalah menjadi Raja Bajak Laut dengan menemukan harta karun legendaris"),
        Anime(8, "Roronoa Zoro", "Santoryu", "Kazuya Nakai", "Male", "One Piece", R.drawable.zoro,"Roronoa Zoro (ロロノア・ ゾロ, Roronoa Zoro) adalah seorang karakter di one piece dalam serial anime dan manga One Piece karya Eiichiro Oda. Ia adalah salah satu tokoh protagonis utama. Ia merupakan anggota Bajak Laut Topi Jerami yang pertama kali bergabung dan hingga saat ini ia dinilai sebagai ancaman terbesar dan anggota paling berbahaya dari kelompoknya setelah sang kapten"),
        Anime(9, "Sanji", "Diable Jambe", "Hiroaki Hirata", "Male", "One Piece", R.drawable.sanji,"\"Kaki Hitam\" Sanji (黒脚・サンジ Kuro ashi no Sanji?) adalah seorang bajak laut merangkap koki dari kelompok Bajak Laut Topi Jerami. Ia merupakan anggota kelima yang bergabung menjadi anggota kru saat kru topi jerami berlabuh di restoran terapung Baratie."),
        Anime(10, "Nami", "Thunderbolt Tempo", "Akemi Okamura", "Female", "One Piece", R.drawable.nami,"Nami (ナミ, Nami) adalah seorang karakter fiksi dari serial anime dan manga One Piece karya Eiichiro Oda. Ia adalah seorang bajak laut dan navigator dari Kelompok Bajak Laut Topi Jerami. Ia merupakan anggota kedua di kelompoknya setelah bergabungnya Roronoa Zoro . Di Arc Baratie, Nami sempat mengkhianati kelompoknya untuk sementara waktu, tetapi akhirnya bergabung kembali menjelang akhir Arc Arlong setelah masa lalu dan tujuannya yang sebenarnya terungkap. Ia memiliki jumlah tebusan saat ini sebesar 366,000,000 Berry."),
        )
}